apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-batch-label-studio
spec:
  schedule: "*/2 * * * *" # toutes les 2 minutes, si on veut faire toutes les minutes : "* * * * *"
  concurrencyPolicy: Forbid # ensure only one pod is running at a time
  jobTemplate:
    spec:
      backoffLimit: 0  # Number of retries before considering the Job as failed
      template:
        spec:
          containers:
          - name: send-batch-label-studio
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - |
                cd /tmp &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/template/correspondance_intitule_nature_activite.json &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/s3_sync_source.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/s3_create_target.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/s3_sync_target.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.sh &&
                chmod +x transform_to_json.sh &&
                export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
                ./transform_to_json.sh 
                echo "ok" &&
            volumeMounts:
            - name: tmp
              mountPath: "/tmp"
            envFrom:
            - configMapRef:
                    name: etl-label-studio-config
            env:
            # from secrets
            - name: LABEL_STUDIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token
                  key: token
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: secretKey
        
            - name: LABEL_STUDIO_PROJECT_ID
              value: "1" 
          restartPolicy: Never
          serviceAccountName: send-batch-label-studio
          volumes:
          - name: tmp
            emptyDir: {}