apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etl-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: etl-monitoring
  namespace: projet-ape