apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etl-test-data-monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/TheAIWizard/ETL-s3.git
    targetRevision: HEAD
    path: etl-test-data-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: user-nrandriamanana
  syncPolicy:
    automated:
      selfHeal: true