apiVersion: batch/v1
kind: Job
metadata:
  name: csv-to-json-job
spec:
  template:
    spec:
      containers:
      - name: csv-to-json-container
        image: inseefrlab/onyxia-python-datascience:py3.10.9
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - |
            cd /tmp &&

            wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.py &&
            chmod +x transform_to_json.py &&
            ./transform_to_json.py --input-file /tmp/ETL-s3/data_gu_check_API.csv --output-file /tmp/ETL-s3/data_gu_check_API.json
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
        env:
        - name: S3_ENDPOINT_URL
          value: "https://minio.lab.sspcloud.fr"  # Replace with your Minio endpoint URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-creds
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-creds
              key: secretKey
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: S3_BUCKET
          value: nrandriamanana  # Replace with your S3 bucket name
        - name: S3_BUCKET_PREFIX
          value: Label Studio/Annotation APE 2024/Extract manuelle   # Replace with your S3 bucket prefix name
      restartPolicy: Never
      serviceAccountName: get-logs-api
      volumes:
      - name: tmp
        emptyDir: {}
