apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: csv-to-json-cronjob
spec:
  schedule: "*/1 * * * *"  # Exécution toutes les minutes 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: csv-to-json-container
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - |
                cd /tmp &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.sh &&
                chmod +x transform_to_json.sh &&
                export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
                ./transform_to_json.sh
            volumeMounts:
            - name: tmp
              mountPath: "/tmp"
            env:
            - name: S3_ENDPOINT_URL
              value: https://minio.lab.sspcloud.fr
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds-service-account
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: S3_BUCKET
              value: nrandriamanana
            - name: S3_BUCKET_PREFIX_TRANSFORM_JSON
              value: "Label Studio/Annotation APE 2024/Batch data json/"
            - name: S3_BUCKET_PREFIX_SOURCE_ANNOTATION
              value: "Label Studio/Annotation APE 2024/Annotation source/"
          restartPolicy: Never
          volumes:
          - name: tmp
            emptyDir: {}
