apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-batch-api
spec:
  schedule: "*/2 * * * *" # toutes les 2 minutes, si on veut faire toutes les minutes : "* * * * *"
  concurrencyPolicy: Forbid # ensure only one pod is running at a time
  jobTemplate:
    spec:
      backoffLimit: 1  # Number of retries before considering the Job as failed
      template:
        spec:
          containers:
          - name: send-batch-label-studio
            image: inseefrlab/onyxia-python-datascience:py3.10.9
            imagePullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - |
                cd /tmp &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/s3_sync_source.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.py &&
                wget https://raw.githubusercontent.com/TheAIWizard/ETL-s3/main/utils/transform_to_json.sh &&
                chmod +x transform_to_json.sh &&
                export MC_HOST_s3=https://$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY@$AWS_S3_ENDPOINT &&
                ./transform_to_json.sh 
                echo "ok" &&
            volumeMounts:
            - name: tmp
              mountPath: "/tmp"
            env:
            - name: S3_ENDPOINT_URL
              value: https://minio.lab.sspcloud.fr  # Replace with your Minio endpoint URL
            - name: AWS_S3_ENDPOINT
              value: minio.lab.sspcloud.fr  # Replace with your Minio endpoint URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: LABEL_STUDIO_SERVICE_ENDPOINT
              value: http://user-nrandriamanana-115611.user.lab.sspcloud.fr # replace with your service endpoint
            - name: LABEL_STUDIO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-label-studio-token
                  key: token
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: S3_BUCKET
              value: projet-ape # Replace with your S3 bucket name
            - name: S3_BUCKET_PREFIX_TRANSFORM_JSON
              value: "Label Studio/Annotation APE 2024/NAF 2008/Batch data json/"   # Replace with your S3 bucket prefix name
            - name: S3_BUCKET_PREFIX_ANNOTATION_SOURCE
              value: "Label Studio/Annotation APE 2024/NAF 2008/Annotation source/"   # Replace with your S3 bucket prefix name
            - name: S3_BUCKET_PREFIX_DEPOT_MANUEL
              value: "Label Studio/Annotation APE 2024/NAF 2008/Extract manuelle/"   # Replace with your S3 bucket prefix name
            - name: S3_BUCKET_PREFIX_ARCHIVE_DEPOT_MANUEL
              value: "Label Studio/Annotation APE 2024/NAF 2008/Extract manuelle/Archive annotations/"   # Replace with your S3 bucket prefix name
          restartPolicy: Never
          serviceAccountName: send-batch-label-studio
          volumes:
          - name: tmp
            emptyDir: {}