apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: persist-target-label-studio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: persist-target-label-studio
  namespace: nrandriamanana # projet-ape